In [1]:
import pandas as pd
df = pd.read_csv(r"D:\PYTHON_FILES\train\train.csv")

In [2]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [4]:
df['Age'] = df['Age'].fillna(
    df.groupby(['Sex', 'Pclass'])['Age'].transform('median')
)
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

df['Cabin'] = df['Cabin'].fillna('No Data')

In [5]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [6]:
df['Embarked'].unique()

<ArrowStringArray>
['S', 'C', 'Q']
Length: 3, dtype: str

In [7]:
df['Pclass'].unique()

array([3, 1, 2])

In [6]:
df['Embarked']= df['Embarked'].replace({'C':'Cherbourg',
                                        'Q': 'Queenstown',
                                         'S': 'Southampton'})
df['Pclass']= df['Pclass'].replace({1:'First Class',
                                        2: 'Second Class',
                                         3: 'Third Class'})

In [7]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,Third Class,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,No Data,Southampton
1,2,1,First Class,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,Cherbourg
2,3,1,Third Class,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,No Data,Southampton
3,4,1,First Class,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,Southampton
4,5,0,Third Class,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,No Data,Southampton

In [8]:
df.drop(columns='PassengerId',inplace=True)

In [9]:
df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,Third Class,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,No Data,Southampton
1,1,First Class,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,Cherbourg
2,1,Third Class,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,No Data,Southampton
3,1,First Class,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,Southampton
4,0,Third Class,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,No Data,Southampton

In [10]:
df.insert(
    loc=df.columns.get_loc('Parch') + 1,  # position right after Parch
    column='FamilyType',
    value=(df['SibSp'] + df['Parch'] + 1).apply(
        lambda x: 'Alone' if x == 1 else ('Small Family' if x <= 4 else 'Large Family')
    )
)

In [11]:
df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,FamilyType,Ticket,Fare,Cabin,Embarked
0,0,Third Class,"Braund, Mr. Owen Harris",male,22.0,1,0,Small Family,A/5 21171,7.2500,No Data,Southampton
1,1,First Class,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,Small Family,PC 17599,71.2833,C85,Cherbourg
2,1,Third Class,"Heikkinen, Miss. Laina",female,26.0,0,0,Alone,STON/O2. 3101282,7.9250,No Data,Southampton
3,1,First Class,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,Small Family,113803,53.1000,C123,Southampton
4,0,Third Class,"Allen, Mr. William Henry",male,35.0,0,0,Alone,373450,8.0500,No Data,Southampton

In [14]:
pip install mysql-connector-python sqlalchemy

Requirement already satisfied: mysql-connector-python in c:\users\teja\anaconda3\lib\site-packages (9.6.0)
Requirement already satisfied: sqlalchemy in c:\users\teja\anaconda3\lib\site-packages (2.0.39)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\teja\anaconda3\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\teja\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [15]:
from sqlalchemy import create_engine

engine = create_engine('mysql+mysqlconnector://root:Hello%4012345@localhost:3306/train')

In [16]:
df.to_sql(name='train', con=engine, if_exists='replace', index=False)

891